Check if channel has messages
Sometimes the channel exists but the "messages" property is undefined. This causes an exception and crash if you don't have a catch. 

Example:

TypeError: Cannot read property 'cache' of undefined
    at MessageCreateAction.handle (/app/node_modules/discord.js/src/client/actions/MessageCreate.js:11:41)
    at Object.module.exports [as MESSAGE_CREATE] (/app/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:219:5)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:835:20)
    at Receiver.emit (events.js:219:5)
    at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:437:14)